services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend-php:
    build: ./backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - backend_storage:/var/www/html/storage
      - backend_cache:/var/www/html/bootstrap/cache
    depends_on:
      - db

  backend-nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - backend_storage:/var/www/html/storage
      - backend_cache:/var/www/html/bootstrap/cache
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-php

  frontend:
    build: ./frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend-nginx

volumes:
  pgdata:
  backend_storage:
  backend_cache:
